# Generated by Django 5.2.4 on 2025-07-18 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_cases', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Associado'),
        ),
        migrations.AlterModelOptions(
            name='case',
            options={},
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_description',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='case',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='case',
            name='client_liquidation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Liquidação ao Cliente'),
        ),
        migrations.AddField(
            model_name='case',
            name='commission_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Comissão'),
        ),
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(default='caso sem título', max_length=255, verbose_name='Título do Caso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='bank_payment_status',
            field=models.CharField(choices=[('Aguardando Pagamento Banco', 'Aguardando Pagamento Banco'), ('Pago pelo Banco', 'Pago pelo Banco'), ('Reembolso Solicitado', 'Reembolso Solicitado'), ('Disputa', 'Disputa')], default='Aguardando Pagamento Banco', max_length=50, verbose_name='Status Pagamento Banco'),
        ),
        migrations.AlterField(
            model_name='case',
            name='bank_response_status',
            field=models.CharField(choices=[('Aguardando Resposta', 'Aguardando Resposta'), ('Aceita', 'Aceita'), ('Negada', 'Negada'), ('Reuniao Solicitada', 'Reunião Solicitada'), ('Contraproposta', 'Contraproposta')], default='Aguardando Resposta', max_length=50, verbose_name='Resposta do Banco'),
        ),
        migrations.AlterField(
            model_name='case',
            name='client_decision',
            field=models.CharField(choices=[('Aguardando Decisão', 'Aguardando Decisão'), ('Aceita', 'Aceita'), ('Rejeita', 'Rejeita')], default='Aguardando Decisão', max_length=50, verbose_name='Decisão do Cliente'),
        ),
        migrations.AlterField(
            model_name='case',
            name='counterproposal_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Contraproposta'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='Criado por (Funcionário)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='current_status',
            field=models.CharField(default='Em tramitação interna', max_length=100, verbose_name='Status Atual'),
        ),
        migrations.AlterField(
            model_name='case',
            name='docusign_status',
            field=models.CharField(choices=[('Não Enviado', 'Não Enviado'), ('Enviado', 'Enviado'), ('Assinado', 'Assinado'), ('Recusado', 'Recusado')], default='Não Enviado', max_length=50, verbose_name='Status DocuSign'),
        ),
        migrations.AlterField(
            model_name='case',
            name='dossier_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio do Dossiê ao Banco'),
        ),
        migrations.AlterField(
            model_name='case',
            name='final_agreement_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio do Acordo Final'),
        ),
        migrations.AlterField(
            model_name='case',
            name='human_analysis_result',
            field=models.CharField(choices=[('Aguardando Análise', 'Aguardando Análise'), ('Viável', 'Viável'), ('Não Viável', 'Não Viável')], default='Aguardando Análise', max_length=50, verbose_name='Resultado Análise Humana'),
        ),
        migrations.AlterField(
            model_name='case',
            name='ia_analysis_result',
            field=models.CharField(choices=[('Aguardando Análise', 'Aguardando Análise'), ('Potencialmente Abusivo', 'Potencialmente Abusivo'), ('Não Abusivo', 'Não Abusivo')], default='Aguardando Análise', max_length=50, verbose_name='Resultado Análise IA'),
        ),
        migrations.AlterField(
            model_name='case',
            name='proposal_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio da Proposta'),
        ),
        migrations.AlterField(
            model_name='case',
            name='technical_report_content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo do Parecer Técnico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='setor_ou_equipe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor/Equipe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Arquivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
