# Generated by Django 5.2.4 on 2025-07-17 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_case_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='current_status',
            field=models.CharField(default='Em tramitação interna', max_length=100, verbose_name='Status Atual'),
        ),
        migrations.CreateModel(
            name='ProcessMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=50, verbose_name='Tipo de Movimento')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('from_sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Do Setor')),
                ('to_sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Para o Setor')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo/Despacho')),
                ('is_internal', models.BooleanField(default=True, verbose_name='Movimento Interno')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Anotações Internas')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to=settings.AUTH_USER_MODEL, verbose_name='Ator')),
                ('associated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='core.document', verbose_name='Documento Associado')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.case', verbose_name='Caso')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
