# Generated by Django 5.2.4 on 2025-07-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_case_client_alter_case_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão do Caso'),
        ),
        migrations.AddField(
            model_name='case',
            name='final_communication_sent',
            field=models.BooleanField(default=False, verbose_name='Comunicação Final Enviada'),
        ),
        migrations.AddField(
            model_name='case',
            name='survey_sent',
            field=models.BooleanField(default=False, verbose_name='Pesquisa de Satisfação Enviada'),
        ),
    ]
