# Generated by Django 5.2.4 on 2025-07-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_case_completion_date_case_final_communication_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='bank_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Código do Banco'),
        ),
        migrations.AddField(
            model_name='case',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Banco'),
        ),
        migrations.AddField(
            model_name='case',
            name='contract_type',
            field=models.CharField(choices=[('renegociacao_consignado', 'Renegociação Consignado INSS'), ('credito_pessoal', 'Crédito Pessoal'), ('financiamento_veicular', 'Financiamento Veicular'), ('financiamento_imovel', 'Financiamento Imóvel'), ('cartao_consignado', 'Cartão Consignado'), ('cartao_beneficio', 'Cartão Benefício')], default='renegociacao_consignado', max_length=50, verbose_name='Tipo de Contrato'),
        ),
    ]
