# Generated by Django 5.2.4 on 2025-07-21 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_case_bank_code_case_bank_name_case_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('renegociacao_credito', 'Renegociação de Crédito'), ('resolucao_conflitos_telecom', 'Resolução de Conflitos - Telecom'), ('outros', 'Outros')], default='renegociacao_credito', max_length=50, verbose_name='Tipo de Caso'),
        ),
        migrations.AddField(
            model_name='case',
            name='parent_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_cases', to='core.case', verbose_name='Caso Pai'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='URL do Arquivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
            preserve_default=False,
        ),
    ]
