# Generated by Django 5.2.4 on 2025-07-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmovement',
            name='request_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Solicitação de Serviço'),
        ),
    ]
