# Generated by Django 5.2.4 on 2025-07-21 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_case_case_type_case_parent_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.CreateModel(
            name='Comunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comunicacao', models.CharField(choices=[('Nota Interna', 'Nota Interna'), ('Email para Cliente', 'Email para Cliente'), ('Notificação para Banco', 'Notificação para Banco')], max_length=50, verbose_name='Tipo de Comunicação')),
                ('destinatario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destinatário (e-mail)')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('corpo', models.TextField(verbose_name='Corpo da Mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicacoes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes', to='core.case', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Comunicação',
                'verbose_name_plural': 'Comunicações',
                'ordering': ['-timestamp'],
            },
        ),
    ]
