# Generated by Django 5.2.4 on 2025-07-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_document_uploaded_by_comunicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='protocol_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='ID do Protocolo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='ID de Cliente'),
        ),
    ]
