# Generated by Django 5.2.4 on 2025-07-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_case_human_analysis_result_case_ia_analysis_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client_decision',
            field=models.CharField(choices=[('Aguardando Decisão', 'Aguardando Decisão'), ('Aceita', 'Aceita'), ('Rejeita', 'Rejeita')], default='Aguardando Decisão', max_length=50, verbose_name='Decisão do Cliente'),
        ),
        migrations.AddField(
            model_name='case',
            name='docusign_status',
            field=models.CharField(choices=[('Não Enviado', 'Não Enviado'), ('Enviado', 'Enviado'), ('Assinado', 'Assinado'), ('Recusado', 'Recusado')], default='Não Enviado', max_length=50, verbose_name='Status DocuSign'),
        ),
        migrations.AddField(
            model_name='case',
            name='proposal_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio da Proposta'),
        ),
    ]
