# Generated by Django 5.2.4 on 2025-07-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_case_protocol_id_customuser_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('FUNCIONARIO', 'Funcionário'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=20, verbose_name='Função'),
        ),
    ]
