# Generated by Django 5.2.5 on 2025-08-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='current_status',
            field=models.CharField(choices=[('AGUARDANDO_DOCUMENTOS', 'Aguardando Documentos'), ('EM_ANALISE_IA', 'Em Análise (IA)'), ('PENDENTE_SOLICITACAO_CONTRATOS', 'Pendente - Solicitação de Contratos'), ('ANALISE_HUMANA', 'Em Análise (Humana)'), ('EM_EXECUCAO_OFICIO', 'Em Execução de Ofício')], default='AGUARDANDO_DOCUMENTOS', max_length=50, verbose_name='Status Atual'),
        ),
    ]
