# Generated by Django 5.2.4 on 2025-07-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_case_client_decision_case_docusign_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='bank_response_status',
            field=models.CharField(choices=[('Aguardando Resposta', 'Aguardando Resposta'), ('Aceita', 'Aceita'), ('Negada', 'Negada'), ('Reuniao Solicitada', 'Reunião Solicitada'), ('Contraproposta', 'Contraproposta')], default='Aguardando Resposta', max_length=50, verbose_name='Resposta do Banco'),
        ),
        migrations.AddField(
            model_name='case',
            name='counterproposal_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Contraproposta'),
        ),
        migrations.AddField(
            model_name='case',
            name='dossier_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio do Dossiê ao Banco'),
        ),
    ]
