# Generated by Django 5.2.5 on 2025-08-25 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_case_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='current_status',
            field=models.CharField(choices=[('ONBOARDING', '1. Onboarding e Preenchimento'), ('VALIDACAO_DOCUMENTAL', '2. Validação Documental'), ('EXTRACAO_DADOS', '3. Extração de Dados dos Contratos'), ('ANALISE_FINANCEIRA_PREL', '4. Análise Financeira Preliminar'), ('PRE_ANALISE_FINAL', '5. Pré-Análise Final'), ('FASE_COMERCIAL', '6. Fase Comercial'), ('PROPOSTA_COMERCIAL', '7. Proposta Comercial'), ('AGUARDANDO_TAXAS', '8. Aguardando Pagamento de Taxas'), ('ANALISE_TECNICA', '9. Análise Técnica Aprofundada'), ('VALIDACAO_E_CONVERSAO', '10. Validação Final e Conversão'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado'), ('AGUARDANDO_OFICIO', 'Aguardando Resolução de Ofício'), ('REANALISE', 'Em Reanálise')], default='ONBOARDING', max_length=100, verbose_name='Status Atual'),
        ),
        migrations.CreateModel(
            name='DocumentValidationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=20, verbose_name='Status da Validação')),
                ('visibilidade_ok', models.BooleanField(default=False, verbose_name='Visibilidade e Iluminação OK')),
                ('legibilidade_ok', models.BooleanField(default=False, verbose_name='Legibilidade do Texto OK')),
                ('frente_e_verso_ok', models.BooleanField(default=False, verbose_name='Frente e Verso/Todas as Páginas OK')),
                ('documento_correto_ok', models.BooleanField(default=False, verbose_name='Documento é o Solicitado OK')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Validação')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da Reprovação')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_check', to='core.document', verbose_name='Documento')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_checks', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Checklist de Validação de Documento',
                'verbose_name_plural': 'Checklists de Validação de Documentos',
            },
        ),
    ]
