# Generated by Django 5.2.4 on 2025-07-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_case_bank_response_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='final_agreement_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio do Acordo Final'),
        ),
    ]
