# Generated by Django 5.2.5 on 2025-08-25 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_case_current_status_documentvalidationcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Template de Checklist')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='checklist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.checklisttemplate', verbose_name='Checklist de Documentos Aplicável'),
        ),
        migrations.CreateModel(
            name='ContractAnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_credito_liberado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do Crédito Liberado')),
                ('valor_total_financiado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Financiado (com taxas)')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Parcela Mensal')),
                ('numero_total_parcelas', models.IntegerField(blank=True, null=True, verbose_name='Número Total de Parcelas')),
                ('taxa_juros_mensal_contrato', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Taxa de Juros Mensal (%)')),
                ('taxa_juros_anual_contrato', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Taxa de Juros Anual (%)')),
                ('cet_anual_contrato', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='CET Anual (%)')),
                ('data_assinatura_contrato', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura do Contrato')),
                ('data_vencimento_primeira_parcela', models.DateField(blank=True, null=True, verbose_name='Vencimento da 1ª Parcela')),
                ('tarifa_cadastro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tarifa de Cadastro (TC)')),
                ('seguro_prestamista', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Seguro Prestamista')),
                ('data_extracao', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_data', to='core.case', verbose_name='Caso Associado')),
                ('dados_extraidos_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dados de Análise de Contrato',
                'verbose_name_plural': 'Dados de Análise de Contratos',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='Nome do Documento Obrigatório')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='É Obrigatório?')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='core.checklisttemplate', verbose_name='Template de Checklist')),
            ],
        ),
    ]
